### PR TITLE
Tests for power capping

### PR DESCRIPTION
**Pull request by fastfadingviolets**

### CODE REVIEW

**Comment by fastfadingviolets** [comment]
https://github.com/hyphacoop/cosmos-release-testing/actions/runs/9100656589

**Comment by fastfadingviolets** [comment]
Run with neutron + stride updates https://github.com/hyphacoop/cosmos-release-testing/actions/runs/9180876521

**Comment by fastfadingviolets** [comment]
Testing the power cap:

* Launch an opt-in chain with 4 validators and a power cap of 50 % (this is 50% in the consumer chain)
* The biggest validator self-delegates in the provider chain in a way that would push it over 50% in the consumer
* Check that the voting powers don't match
* Check that  validator's voting power in the consumer chain is 50

Testing the set cap:

* Launch an opt-in chain with 4 validators and a cap of 4
* Opt a new validator in
* Ensure it doesn't make it into the validator set

**Review by dasanchez — APPROVED** [review]
Thanks @fastfadingviolets !

**Pull request merged**
